import thumbnail1 from "./components/images/profilePic.png";
import thumbnail2 from "./components/images/Rectangle44.png";
import thumbnail3 from "./components/images/Rectangle46.png";
import thumbnail4 from "./components/images/Rectangle48.png";
import thumbnail5 from "./components/images/Rectangle49.png";

const data = [
  {
    image:  thumbnail1 ,
    timeStamp: "1:15",
    title: "Why Web2 sucks?",
    date: "22 Jan 2022",
    views: "69",
    comments: "5",
    likes: "30",
  },
  {
    image:  thumbnail2 ,
    timeStamp: "1:05",
    title: "You shouldn't use web2",
    date: "16 Jan 2022",
    views: "56",
    comments: "5",
    likes: "45",
  },
  {
    image:  thumbnail3 ,
    timeStamp: "1:25",
    title: "web 2 is the worst",
    date: "12 Jan 2022",
    views: "45",
    comments: "5",
    likes: "23",
  },
  {
    image:  thumbnail4 ,
    timeStamp: "1:05",
    title: "You still using web2",
    date: "16 Jan 2022",
    views: "56",
    comments: "5",
    likes: "25",
  },
  {
    image:  thumbnail5 ,
    timeStamp: "1:25",
    title: "Web2 makes me sick",
    date: "12 Jan 2022",
    views: "45",
    comments: "5",
    likes: "27",
  },
  {
    image:  thumbnail1 ,
    timeStamp: "1:15",
    title: "Why Web2 sucks?",
    date: "22 Jan 2022",
    views: "69",
    comments: "5",
    likes: "30",
  },
  {
    image:  thumbnail2 ,
    timeStamp: "1:05",
    title: "You shouldn't use web2",
    date: "16 Jan 2022",
    views: "56",
    comments: "5",
    likes: "45",
  },
  {
    image:  thumbnail3 ,
    timeStamp: "1:25",
    title: "web 2 is the worst",
    date: "12 Jan 2022",
    views: "45",
    comments: "5",
    likes: "23",
  },
  {
    image:  thumbnail4 ,
    timeStamp: "1:05",
    title: "You still using web2",
    date: "16 Jan 2022",
    views: "56",
    comments: "5",
    likes: "25",
  },
  {
    image:  thumbnail5 ,
    timeStamp: "1:25",
    title: "Web2 makes me sick",
    date: "12 Jan 2022",
    views: "45",
    comments: "5",
    likes: "27",
  },
  {
    image:  thumbnail1 ,
    timeStamp: "1:15",
    title: "Why Web2 sucks?",
    date: "22 Jan 2022",
    views: "69",
    comments: "5",
    likes: "30",
  },
  {
    image:  thumbnail2 ,
    timeStamp: "1:05",
    title: "You shouldn't use web2",
    date: "16 Jan 2022",
    views: "56",
    comments: "5",
    likes: "45",
  },
  {
    image:  thumbnail3 ,
    timeStamp: "1:25",
    title: "web 2 is the worst",
    date: "12 Jan 2022",
    views: "45",
    comments: "5",
    likes: "23",
  },
  {
    image:  thumbnail4 ,
    timeStamp: "1:05",
    title: "You still using web2",
    date: "16 Jan 2022",
    views: "56",
    comments: "5",
    likes: "25",
  },
  {
    image:  thumbnail5 ,
    timeStamp: "1:25",
    title: "Web2 makes me sick",
    date: "12 Jan 2022",
    views: "45",
    comments: "5",
    likes: "27",
  },
];

export default data;
